### ISSUE TITLE
k8s/Deployment的完整定义

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/share#8]
在了解基本概念以及解析了dashboard的yaml定义后，我们来看看一个Deployment的完整定义。
# Deployment定义
```yaml
kind: Deployment                            # Require，类型
apiVersion: apps/v1beta2                    # Require，yaml格式版本
metadata:                                   # Require，元数据
  labels:                                   # 标签列表
    your-key: string
  annotation:                               # 注解，可以用于限制带宽、请求速率等
    your-annotation: string                 
  name: string                              # Require，Pod名称
  namespace: string                         # Require，命名空间，默认default
spec:                                       # Require，Pod中容器的详细说明
  replicas: number                          # Require，副本个数，0为删除
  revisionHistoryLimit: number              # 表示历史版本保留的个数，用于回滚，默认10
  selector:                                 # Require，选择器
    matchLabels:                            # Require，至少选择一个Label
      your-key: string                      # 标签，需要与下面的保持一直
  template:                                 # 最核心的部分，Pod的定义，至少要有一个Label
    metadata:                               # Require，Pod元数据
      labels:
        your-key: string
    spec:                                   # Require，容器规格说明，定义容器的属性
      containers:
      - name: string                        # Require，容器名字，必填
        image: string                       # Require，镜像
        imagePullPolicy: string             # 镜像拉去策略，可选Always、Never、IfNotPresent，默认Always
        ports:                              # 容器暴露端口定义
        - hostPort: string                  # 容器所在主机的端口号，通常不设置
          containerPort: number             # 容器端口
          protocol: TCP                     # 端口协议，支持TCP、UDP，默认是TCP
          name: string                      # 端口名称
        command:                            # 启动命令，若是没指定，则使用镜像打包时的启动命令
          - string
        args:                               # 容器启动的命令参数列表
          - string
        workingDir: string                  # 容器工作目录
        env:                                # 容器环境变量
        - name: string
          value: string
        resources:                          # 资源限制
          limits:
          - cpu: string                     # 最大可用CPU，单位为内核数，同docker参数--cpu-shares
            memory: string                  # 最大可用内存，单位MiB、GiB，同docker参数--memory
          requests:
          - cpu: string                     # 启动可用CPU内核数，同docker参数--cpu-shares
            memory: string                  # 启动可用内存，单位MiB、GiB，同docker参数--memory
        volumeMounts:                       # 挂载到容器内部的存储卷配置
        - name: string                      # 卷名称
          mountPath: string                 # 卷在容器内Mount的绝对路径，不多于512字符
          readOnly: boolean                 # 是否只读模式，默认是false
        livenessProbe: object               # 健康检测，见livenessProbe
          initialDelaySeconds: 30           # 容器启动后进行首次探测的时间，单位s
          timeoutSeconds: 30                # 超时时间30s
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          type: object                      # 检测类型，见livenessProbe
      volumes:                              # 该Pod上定义的共享存储卷列表
      - name: string                        # 共享存储卷名称
        type: object                        # 存储卷类型，Volumes节点
      serviceAccountName: string            # 绑定ServiceAccount账号来操作
      restartPolicy:                        # 重启策略，可选值有Always、OnFailure，默认Always
      dnsPolicy: ClusterFirst               # dns解析
      restartPolicy: Always                 # 重启策略
      securityContext: {}                   # 
      tolerations:                          # 部署策略
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```

# volumes
该Pod上定义的共享存储卷列表，支持以下定义：
## emptyDir
临时目录，生命周期跟Pod相同，格式如下：
```yaml
volumes:
- name: string
  emptyDir:{}
```

## hostPath
Pod所在宿主机目录，格式如下：
```yaml
volumes:
- name: string
  hostPath:
    path: string
```
## secret
挂载集群预定义的secret对象到容器内部，其格式如下：
```yaml
volumes:
- name: string
  secret: 
    defaultMode: number
    secretName: string
```
## configMap
挂载集群预定义的configMap对象到容器内部，其格式如下：
```yaml
volumes:
- name: string
  configMap: object
```
## 其他
除了以上共享存储卷之外，目前还支持
- aws、gce等云的存储
- cephfs、glusterfs等分布式存储

# livenessProbe
用于检测容器的存活，目前支持：
## httpGet
```yaml
livenessProbe:                
  httpGet:
    path: /
    port: port
    scheme: HTTPS
    httpHeaders:
    - name: header
      value: string
```

## tcpSocket
```yaml
livenessProbe:                
  tcpSocket:
    port: port
```

## exec
```yaml
livenessProbe:      
  exec:
    command:
    - cat
    - /tmp/healthy
```

## named port
```yaml
ports:
- name: liveness-port
  containerPort: 8080
  hostPort: 8080

livenessProbe:
  httpGet:
    path: /healthz
    port: liveness-port
```

> 有时候，容器启动时需要耗费大量时间（比如加载大量数据），，导致还未启动完成就被杀死重启，这时可以使用`readinessProbe`代替，其定义跟`livenessProbe`一样
